name: WoT
markdown: kramdown

# uncomment if in root
baseurl: "/wot-marketing"

navigation:
# - title: âŒ‚
# - title: Home
 - title: Welcome
   url: /wot-marketing/
 - title: Working Group
   url: /wot-marketing/wg/
 - title: Interest Group
   url: /wot-marketing/ig/
 - title: Community Group
   url: /wot-marketing/cg/
 - title: Activities
   subnavigation:
   - title: General
     url: /wot-marketing/activities/general/
   - title: Thing Description
     url: /wot-marketing/activities/tf-td/
   - title: Architecture
     url: /wot-marketing/activities/tf-architecture/
   - title: Security
     url: /wot-marketing/activities/tf-security/
   - title: Scripting API
     url: /wot-marketing/activities/tf-scripting/
   - title: Discovery
     url: /wot-marketing/activities/tf-discovery/
 - title: Developers
   url: /wot-marketing/developers/
 - title: More
   subnavigation:
   - title: Getting Started
     url: /wot-marketing/getting-started/
#   - title: Calls and Meetings
#     url: https://www.w3.org/WoT/IG/wiki/
